### ISSUE TITLE
稼働時間を把握する

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/projects#140]
責任者：亀井
目的：タスクの割り振りや期限を決めるときの参考にする

- [x] フォーマット作成
期限：9/30 AM
- [x] 書き込みを依頼
期限：9/30 AM
- [x] 時間を書き込む(亀井)
期限：10/2
- [x] 時間を書き込む(中西)
期限：10/2
- [x] 全て完了したら亀井に報告
期限：全て完了したら

**Comment by kameiatsushi** [comment]
## 稼働可能時間
曜日 | 亀井 | 詳細 | 中西 | 詳細
-- | -- | --
日AM | x | 休み | |
日PM | x | 休み | |
月AM | x | revoneo | |
月PM | 15:00~19:00 | 夜は小倉スクール | |
火AM | x | revoneo | |
火PM | 15:00~|
水AM ||
水PM ||
木AM ||
木PM ||
金AM ||
金PM ||
土AM ||
土PM ||

**Comment by kameiatsushi** [comment]
授業に時間がとられている印象
全体としての稼働時間も少ない
でも、稼働可能時間内はちゃんと稼働すれば今よりは仕事は進みそう
無駄な時間はけっこうあると思うので、そこを削らねば

**Comment by NakanishiHiroki** [comment]
9:00~12:00の時間を確保できているにも関わらずタスクをこなせていない。(祖父母問題があるということを加味しても動けていない。)
移動時間が長い為その時間も稼働する習慣をつけなければ。(文献から知識をつける時間などに充てる)
バイトはやめるべき。一日拘束されるので相性が悪い。
