### ISSUE TITLE
20191022 授業log《新谷さん》

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/projects#173]
授業担当：亀井
授業目的：論理的思考、演算能力を養う
授業目標：ゲームを楽しむ
参照：[数字当てゲーム](https://github.com/life-lab-kyoto/projects/issues/108)

参加生徒：伊村道瑠(みちるちゃん)、宇野珠央(たまおちゃん)

**Comment by NakanishiHiroki** [comment]
## 今週の一問
アルファベット直線曲線 #176

**Comment by kameiatsushi** [comment]
# 振り返り
