### ISSUE TITLE
20191030 授業log ディスカッション 人工脳は許されるか

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/projects#180]
授業担当：
授業目的：自分の意見を持ってディスカッションする
授業目標：いい質問を出す
参照：[ミニ脳は倫理の境界を超えた？](https://www.newsweekjapan.jp/stories/world/2019/10/post-13266.php)：[docs](https://docs.google.com/document/d/1ZzKYm6-Fry-J9TOUV2oyNROdyfiJVGycMHUVuoIZ4x8/edit?usp=sharing)

参加生徒：亀井健史、泉龍征、西村柑太、田内彩
ゲスト：
```
- よろづ支援拠点 津賀拝

- 朝日新聞大阪本社販売局
流通開発部宣伝 兼 代表室マーケティング担当
有馬 誠生
```

**Comment by kameiatsushi** [comment]
# 導入

**Comment by kameiatsushi** [comment]
# 振り返り
亀井
```
哲学は楽しい
話を広げるのは、
```

中西
```
```
