### ISSUE TITLE
20191101 授業log National Economyをやろう

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/projects#197]
授業担当：亀井
授業目的：考えることを楽しむ
授業目標：50pt以上とる
参照：

参加生徒：田内彩、泉龍征

**Comment by kameiatsushi** [comment]
# 導入
久しぶりにNational Economyやろう
常に考えることが大事
全力で頭を使って遊べる人が賢くなっていく

# 実際にプレイ

# 学んだことを話す
ゲームをプレイする上で大事なことを振り返る
その知見を日常の学びに結びつける

- 序盤が大事、コストが低いうちに戦力を確保する
→ 若いうちにスキルを磨く　失敗してもリスクが小さい今のうちに色々チャレンジしておく
- 手札を変える
→ 色々な選択肢を見てから選ぶ　固定の友達だけでなく、色々な人と付き合ってみる

**Comment by kameiatsushi** [comment]
# 振り返り
亀井
```
僕らがやっていて楽しいことを続けていきたい
こういったゲームなども積極的に流行らせたい
土日にゲームをしに来てくれるようになるといいな
そんな文化を作りたい
```
