### ISSUE TITLE
20191029 授業log《新谷》

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/projects#198]
授業担当：亀井
授業目的：論理的思考を養う
授業目標：
参照：[数字当てゲーム](https://github.com/life-lab-kyoto/projects/issues/108)

参加生徒：りこ、あやは、みちる、たまお、わか

**Comment by kameiatsushi** [comment]
# 導入
楽しくなければ効率が悪い
楽しんでやっていると、頭がよく働くので記憶に定着しやすい
処理能力も上がるので、解ける問題数も増え、経験値が貯まりやすい
頭を使うゲームは普段の勉強効率にも繋がるので、ぜひ日常に取り入れて欲しい
数字を使ったゲームはどこでもできるので、ぜひ家や学校でやって欲しい

# 数字当てゲーム
## ゲームの進行
1. 質問順を決める
1. 各プレイヤーは２桁の自然数を決める
1. 質問者がYes or Noで答えられる質問をする。質問者含む各プレイヤーは質問に答える
1. 質問者の次のプレイヤーから順にアタックかパスを宣言する（質問者はアタック不可）
1. アタックが失敗すれば、アタックされたプレイヤーは反撃可能
1. 全員がアタック or パスを終えたら、次の質問者へ移る
1. プレイヤーが最後の1人になるまで、3 ~ 6を繰り返す

## プレイヤーができる行動
- 質問：順番が回ってきたら、Yes or Noで答えられる質問を１つできる
- アタック： プレイヤーを1人指名し、数字を推測して宣言する。当たれば相手プレイヤーは負け抜け
外せば相手プレイヤーから反撃される
- パス：アタックをしないで次のプレイヤーに回す

## 禁止事項
- 数字や言い方を変えただけの同じ類の質問を２連続でする
ex. 奇数ですか（2の倍数ですか）？ → 3の倍数ですか？
- 1度のターンに同じプレイヤーにアタックする

## 使える質問例
- 数の大小
ex. 50より大きいですか？
- 倍数
ex. 3の倍数ですか？, 偶数(or奇数)ですか？
- 約数の個数
ex. 約数は3個以上ですか？, 素数ですか？
- 約数の計算
ex. 約数の和が50以上ですか？
- 各位の計算（一の位 or 十の位）
ex. 十の位が偶数ですか？
- 各位の計算（一の位 and 十の位）
ex. 一の位と十の位の和が10以上ですか？ 

# 今週の一問

**Comment by kameiatsushi** [comment]
# 振り返り
亀井
```
試しに１回のつもりだったが、それで一時間かかったので、そこで終わった
1時間かかったが、それだけ集中して絞りこんでいたので良しとしてもいいだろう
新谷家でもやっているらしいので、これはうまく設計すれば流行らせることはできるかも
```
