### ISSUE TITLE
20191106 授業log 生産性って？

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/projects#205]
授業担当：亀井
授業目的：文章を読む力を伸ばす
授業目標：文章についてわからないところを質問する
参照：[News Cover マイクロソフトが日本で週休3日制度を開始](https://github.com/life-lab-kyoto/projects/issues/207)：[docs](https://docs.google.com/document/d/1TAKSeGGFQjPm0_Cbs6ba64jKbnuC-ZVSkgyxCu1wJQQ/edit?usp=sharing)

参加生徒：田内彩、西村柑太

**Comment by kameiatsushi** [comment]
# 導入

**Comment by NakanishiHiroki** [comment]
[なぜ過労死が起こるのか](https://roudou-pro.com/columns/48/#toc_anchor-1-1-4)


示唆
有望
マネージャーって誰？
リソース
過労
残業って何？
模索
奨励

**Comment by kameiatsushi** [comment]
# 振り返り
亀井
```
最初、英語に抵抗を感じていたようだが、ディスカッションになると調子が出てきた
ディスカッションはレギュラー授業にしていこう
ただ、ディスカッション
```
