### ISSUE TITLE
20191120 授業log トリビアルの海

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/projects#219]
授業担当：中西
授業目的：日常では得る機会が無いだけで面白い知識はそこらには転がっているということを知る
授業目標：へぇーってなる
参照：#223 [トリビアの泉](https://www.youtube.com/watch?v=8hU_2Okagco)

参加生徒：亀井健史, 田内彩, 西村柑太

**Comment by NakanishiHiroki** [comment]
## 導入

**Comment by kameiatsushi** [comment]
# 振り返り
亀井
```
1つの記事あたりにかける時間は20分ぐらいが適切かも
複の

```

中西
```
```
