### ISSUE TITLE
2019 11/27~12/4 文賢

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/projects#282]
責任者：亀井
目的：収入源。将来事業を展開するときのために知見をためておく

- [x] タスクブレイクダウン
ステータス：未着手
期限：11/30

## camecha改善
- [ ] camecha改善点をリストアップ
ステータス：未着手
期限：11/30
- [ ] camechaの変更点を文章にまとめる
ステータス：未着手
期限：11/30
- [x] 例文を列挙する
ステータス：done
期限：16:00
- [ ] 「名詞、副詞可能」は副詞として認識する
ステータス：未着手
期限：

**Comment by kameiatsushi** [comment]
# 文賢MTG
## camecha改善
camechaの修正点をまとめる
どこに影響あるか知りたい

## 新チェック案
## 誤チェックシート
再現せずが再現してる
本番環境でチェックする
66, 101, 102

66は辞書対応
101, 102に関してはissue作成する(リンクをシートに貼る)

## タスク追加
- camecha改善案に追加
「動詞の連用形 ＋ 名詞」は1単語の名詞になる
例：流しそうめん、かき氷

**Comment by kameiatsushi** [comment]
# 主語がないチェック例文
- その本が良い本だと思う
- 彼は美しい絵を買った
- 二郎が売っている本を買った
- 太郎が二郎の書いた本を三郎に見せた

**Comment by NakanishiHiroki** [comment]
## チェック例文
- その本が良い本だと思う。
- 次郎が売っている本を買った。
- 太郎は次郎が書いた本を三郎に見せたと彼は伝えた。
- おまけが欲しくてそのお菓子を買った。
- 私が買った車に彼が乗った。
- 太郎は次郎が書いた本を三郎に見せた人と話した。
- 太郎はとても元気で隣の次郎は病弱だ。
- 太郎は早起きする次郎が寝坊したので驚いた
- 太郎は早起きする次郎が寝坊したので驚いた人を軽蔑する
- 太郎は臆病で照れ屋な次郎と話す
- 太郎は元気で次郎は病弱だ

**Comment by kameiatsushi** [comment]
# 次回報告内容
## camechaの改善
