### ISSUE TITLE
20200128 授業log SS水平思考クイズ

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/projects#349]
授業担当：中西
授業目的：
授業目標：
参照：#356

参加生徒：伊村道瑠, 宇野珠央, 松岡和佳, 植村彩葉, 新谷珠央, 新谷心苗

**Comment by NakanishiHiroki** [comment]
# 教材
![SS蜆蠑柔page-0001](https://user-images.githubusercontent.com/49800056/73235667-b5f6a800-41d2-11ea-8f99-fd343af0d213.jpg)
![SS蜆蠑柔page-0002](https://user-images.githubusercontent.com/49800056/73235669-ba22c580-41d2-11ea-9c99-0580598d6b0e.jpg)
