### ISSUE TITLE
[記事]新型コロナウイルス　世界に広がる東洋人嫌悪

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/projects#373]
カテゴリ：#81
授業目的：
授業目標：異文化理解：差別に関して考えることが出来る

謎：

参考：[新型コロナウイルス　世界に広がる東洋人嫌悪](https://www.newsweekjapan.jp/stories/world/2020/02/post-92304_1.php)
LIFE LAB動画：

**Comment by kameiatsushi** [comment]
#372 と被っているのでclose
